name: "Pull Request Docs Check"
on:
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
          python-version: ${{ matrix.python-version }}
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
